repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.34.0
    hooks:
      - id: yamllint
        args: [--strict]

  - repo: local
    hooks:
      - id: docker-compose-lint
        name: docker-compose config
        entry: docker-compose -f docker-compose.yml config
        language: system
        files: ^docker-compose\.(yml|yaml)$