/* tslint:disable */
/* eslint-disable */
/**
 * Image Processor API
 * OpenAPI specification for Image Processor backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DirEntry
 */
export interface DirEntry {
    /**
     * 
     * @type {string}
     * @memberof DirEntry
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof DirEntry
     */
    'image_count': number;
    /**
     * 
     * @type {number}
     * @memberof DirEntry
     */
    'dir_count': number;
}

