/* tslint:disable */
/* eslint-disable */
/**
 * Image Processor API
 * OpenAPI specification for Image Processor backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ExtrasBatchParams
 */
export interface ExtrasBatchParams {
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtrasBatchParams
     */
    'operations': Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtrasBatchParams
     */
    'images': Array<string>;
}

