/* tslint:disable */
/* eslint-disable */
/**
 * Image Processor API
 * OpenAPI specification for Image Processor backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetDefaultPath200Response
 */
export interface GetDefaultPath200Response {
    /**
     * 
     * @type {string}
     * @memberof GetDefaultPath200Response
     */
    'path': string;
}

