/* tslint:disable */
/* eslint-disable */
/**
 * Image Processor API
 * OpenAPI specification for Image Processor backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetImageDialog200Response
 */
export interface GetImageDialog200Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof GetImageDialog200Response
     */
    'dialog': Array<string>;
}

