/* tslint:disable */
/* eslint-disable */
/**
 * Image Processor API
 * OpenAPI specification for Image Processor backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ImageResponse
 */
export interface ImageResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof ImageResponse
     */
    'images': Array<string>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ImageResponse
     */
    'parameters': { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof ImageResponse
     */
    'info': string;
}

