/* tslint:disable */
/* eslint-disable */
/**
 * Image Processor API
 * OpenAPI specification for Image Processor backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Img2ImgRequest
 */
export interface Img2ImgRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof Img2ImgRequest
     */
    'init_images': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Img2ImgRequest
     */
    'mask'?: string;
    /**
     * 
     * @type {string}
     * @memberof Img2ImgRequest
     */
    'prompt': string;
    /**
     * 
     * @type {string}
     * @memberof Img2ImgRequest
     */
    'negative_prompt'?: string;
    /**
     * 
     * @type {number}
     * @memberof Img2ImgRequest
     */
    'steps'?: number;
    /**
     * 
     * @type {number}
     * @memberof Img2ImgRequest
     */
    'cfg_scale'?: number;
    /**
     * 
     * @type {number}
     * @memberof Img2ImgRequest
     */
    'denoising_strength'?: number;
}

