/* tslint:disable */
/* eslint-disable */
/**
 * Image Processor API
 * OpenAPI specification for Image Processor backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProgressResponse
 */
export interface ProgressResponse {
    /**
     * 
     * @type {string}
     * @memberof ProgressResponse
     */
    'current_image': string;
    /**
     * 
     * @type {number}
     * @memberof ProgressResponse
     */
    'progress': number;
    /**
     * 
     * @type {number}
     * @memberof ProgressResponse
     */
    'eta_relative': number;
}

