/* tslint:disable */
/* eslint-disable */
/**
 * Image Processor API
 * OpenAPI specification for Image Processor backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SpeakerMeta
 */
export interface SpeakerMeta {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof SpeakerMeta
     */
    'speaker_colors': { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof SpeakerMeta
     */
    'speaker_names': { [key: string]: string; };
}

